# Generated by Django 4.2.20 on 2025-04-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatbot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('data_source', models.CharField(choices=[('text', 'Text'), ('document', 'Document'), ('url', 'URL')], max_length=20)),
                ('vector_store_path', models.CharField(blank=True, max_length=500, null=True)),
                ('model', models.CharField(choices=[('gpt', 'GPT'), ('bert', 'BERT'), ('llama', 'LLaMA')], max_length=50)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_image', models.BinaryField(null=True)),
                ('starter_messages', models.JSONField(default=dict)),
                ('quick_actions', models.JSONField(default=dict)),
                ('target_audience', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_information', models.JSONField(default=dict)),
                ('cta_link', models.URLField(blank=True, max_length=500, null=True)),
                ('user_id', models.IntegerField()),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
