# Generated by Django 4.2.20 on 2025-04-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchatbot',
            old_name='target_audience',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='userchatbot',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='userchatbot',
            name='lead_information',
        ),
        migrations.RemoveField(
            model_name='userchatbot',
            name='model',
        ),
    ]
